import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`font-sans ${inter.variable}`}>
                <main className="flex min-h-screen flex-col items-center justify-center">
                    <div className="container flex flex-col items-center justify-center px-4 py-16 ">
                        {children}
                    </div>
                </main>
            </body>
        </html>
    );
}
